from .ApplicationView import ApplicationView
#from .CellularAutomatonView import CellularAutomatonView
from .AnimationSettingsView import AnimationSettingsView

from Domain.CellularAutomaton import CellularAutomaton

from Interfaces.GraphicalUserInterface import GraphicalUserInterface